In [124]:
import pandas as pd

dataset_train = pd.read_csv(
    "../files/input/train_data.csv.zip",
    index_col=False,
    compression="zip",
)
dataset.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,310000,1,3,1,32,0,0,0,0,0,...,84373,57779,14163,8295,6000,4000,3000,1000,2000,0
1,10000,2,3,1,49,-1,-1,-2,-1,2,...,1690,1138,930,0,0,2828,0,182,0,1
2,50000,1,2,1,28,-1,-1,-1,0,-1,...,45975,1300,43987,0,46257,2200,1300,43987,1386,0
3,80000,2,3,1,52,2,2,3,3,3,...,40748,39816,40607,3700,1600,1600,0,1600,1600,1
4,270000,1,1,2,34,1,2,0,0,2,...,22448,15490,17343,0,4000,2000,0,2000,2000,0

In [125]:
dataset_train.rename(columns={"default payment next month": "default"}, inplace=True)

dataset_train.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,10748,310000,1,3,1,32,0,0,0,0,...,84373,57779,14163,8295,6000,4000,3000,1000,2000,0
1,12574,10000,2,3,1,49,-1,-1,-2,-1,...,1690,1138,930,0,0,2828,0,182,0,1
2,29677,50000,1,2,1,28,-1,-1,-1,0,...,45975,1300,43987,0,46257,2200,1300,43987,1386,0
3,8857,80000,2,3,1,52,2,2,3,3,...,40748,39816,40607,3700,1600,1600,0,1600,1600,1
4,21099,270000,1,1,2,34,1,2,0,0,...,22448,15490,17343,0,4000,2000,0,2000,2000,0

In [126]:
dataset_train.pop("ID")

dataset_train.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,310000,1,3,1,32,0,0,0,0,0,...,84373,57779,14163,8295,6000,4000,3000,1000,2000,0
1,10000,2,3,1,49,-1,-1,-2,-1,2,...,1690,1138,930,0,0,2828,0,182,0,1
2,50000,1,2,1,28,-1,-1,-1,0,-1,...,45975,1300,43987,0,46257,2200,1300,43987,1386,0
3,80000,2,3,1,52,2,2,3,3,3,...,40748,39816,40607,3700,1600,1600,0,1600,1600,1
4,270000,1,1,2,34,1,2,0,0,2,...,22448,15490,17343,0,4000,2000,0,2000,2000,0

In [127]:
print(dataset_train.shape[0])

21000

In [128]:
dataset_train.isna().sum()

LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
default      0
dtype: int64

In [129]:
dataset = dataset_train.dropna()

dataset_train.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,310000,1,3,1,32,0,0,0,0,0,...,84373,57779,14163,8295,6000,4000,3000,1000,2000,0
1,10000,2,3,1,49,-1,-1,-2,-1,2,...,1690,1138,930,0,0,2828,0,182,0,1
2,50000,1,2,1,28,-1,-1,-1,0,-1,...,45975,1300,43987,0,46257,2200,1300,43987,1386,0
3,80000,2,3,1,52,2,2,3,3,3,...,40748,39816,40607,3700,1600,1600,0,1600,1600,1
4,270000,1,1,2,34,1,2,0,0,2,...,22448,15490,17343,0,4000,2000,0,2000,2000,0

In [130]:
print(dataset_train.shape[0])

21000

In [131]:
dataset_train['EDUCATION'] = dataset_train['EDUCATION'].apply(lambda x: "others" if x > 4 else x)

In [132]:
y_train=dataset_train.copy()
y_train=y_train.pop("default")

y_train

0        0
1        1
2        0
3        1
4        0
        ..
20995    0
20996    0
20997    0
20998    0
20999    0
Name: default, Length: 21000, dtype: int64

In [133]:
##x_train=dataset_train[dataset_train.columns()-"default"]
##x_train
y_train

0        0
1        1
2        0
3        1
4        0
        ..
20995    0
20996    0
20997    0
20998    0
20999    0
Name: default, Length: 21000, dtype: int64

In [134]:
x_train = dataset_train.copy()
x_train.pop("default")
x_train

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,310000,1,3,1,32,0,0,0,0,0,...,110375,84373,57779,14163,8295,6000,4000,3000,1000,2000
1,10000,2,3,1,49,-1,-1,-2,-1,2,...,-748,1690,1138,930,0,0,2828,0,182,0
2,50000,1,2,1,28,-1,-1,-1,0,-1,...,46257,45975,1300,43987,0,46257,2200,1300,43987,1386
3,80000,2,3,1,52,2,2,3,3,3,...,40101,40748,39816,40607,3700,1600,1600,0,1600,1600
4,270000,1,1,2,34,1,2,0,0,2,...,20924,22448,15490,17343,0,4000,2000,0,2000,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20995,140000,2,2,1,27,2,-1,-1,-1,0,...,776,1580,804,728,752,800,1580,0,700,700
20996,130000,1,2,2,41,0,0,0,0,0,...,123746,123107,42897,39378,4442,5200,5012,2500,5000,2000
20997,50000,1,3,2,23,0,0,0,0,0,...,36023,28967,29829,30046,1973,1426,1001,1432,1062,997
20998,90000,2,3,2,25,0,0,0,0,0,...,5613,5613,10113,10113,3000,3000,0,4500,0,3440
20999,120000,1,2,2,31,0,0,0,0,0,...,109786,104000,121427,116652,5326,5059,4000,120203,5000,5000

In [135]:
dataset_train

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,310000,1,3,1,32,0,0,0,0,0,...,84373,57779,14163,8295,6000,4000,3000,1000,2000,0
1,10000,2,3,1,49,-1,-1,-2,-1,2,...,1690,1138,930,0,0,2828,0,182,0,1
2,50000,1,2,1,28,-1,-1,-1,0,-1,...,45975,1300,43987,0,46257,2200,1300,43987,1386,0
3,80000,2,3,1,52,2,2,3,3,3,...,40748,39816,40607,3700,1600,1600,0,1600,1600,1
4,270000,1,1,2,34,1,2,0,0,2,...,22448,15490,17343,0,4000,2000,0,2000,2000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20995,140000,2,2,1,27,2,-1,-1,-1,0,...,1580,804,728,752,800,1580,0,700,700,0
20996,130000,1,2,2,41,0,0,0,0,0,...,123107,42897,39378,4442,5200,5012,2500,5000,2000,0
20997,50000,1,3,2,23,0,0,0,0,0,...,28967,29829,30046,1973,1426,1001,1432,1062,997,0
20998,90000,2,3,2,25,0,0,0,0,0,...,5613,10113,10113,3000,3000,0,4500,0,3440,0
20999,120000,1,2,2,31,0,0,0,0,0,...,104000,121427,116652,5326,5059,4000,120203,5000,5000,0

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
# Bloque 1: Identificar las columnas categóricas
categorical_columns = ['SEX', 'EDUCATION', 'MARRIAGE']

# Bloque 2: Preprocesamiento de variables categóricas
# Usaremos One-Hot Encoding para las columnas categóricas
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),  # Imputar valores faltantes si existieran
    ('onehot', OneHotEncoder(handle_unknown='ignore'))    # Aplicar One-Hot Encoding
])

# Bloque 3: Crear el ColumnTransformer para aplicar transformaciones específicas
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_columns)  # Transformar solo las categóricas
    ],
    remainder='passthrough'  # Mantener las columnas numéricas sin cambios
)

# Bloque 4: Modelo de Bosques Aleatorios
random_forest_model = RandomForestClassifier(
    n_estimators=100,        # Número de árboles
    max_depth=None,          # Sin límite para la profundidad de los árboles
    random_state=42          # Asegurar reproducibilidad
)

# Bloque 5: Crear el Pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),  # Preprocesar los datos
    ('classifier', random_forest_model)  # Modelo de Bosques Aleatorios
])

# Bloque 6: Entrenar el Pipeline con el conjunto de entrenamiento
pipeline.fit(x_train, y_train)

# Bloque 7: Probar el Pipeline con el conjunto de prueba
#predictions = pipeline.predict(x_test)

# Mostrar un ejemplo de las predicciones
#print("Predicciones de prueba:", predictions[:10])

NameError: name 'BaseEstimator' is not defined

In [145]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd

# Bloque 1: Crear un transformador personalizado para castear a entero
class CastToInteger(BaseEstimator, TransformerMixin):
    def __init__(self, columns):
        self.columns = columns

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        for col in self.columns:
            X[col] = X[col].astype(str)  # Convertir a entero
        return X

# Bloque 2: Identificar las columnas categóricas
categorical_columns = ['SEX', 'EDUCATION', 'MARRIAGE']

# Bloque 3: Preprocesamiento de variables categóricas
# Usamos un transformador personalizado para castear y luego aplicar One-Hot Encoding
categorical_transformer = Pipeline(steps=[
    ('cast_to_int', CastToInteger(categorical_columns)),  # Castear columnas categóricas a entero
    ('imputer', SimpleImputer(strategy='most_frequent')),  # Imputar valores faltantes si existieran
    ('onehot', OneHotEncoder(handle_unknown='ignore'))    # Aplicar One-Hot Encoding
])

# Bloque 4: Crear el ColumnTransformer para aplicar transformaciones específicas
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_columns)  # Transformar solo las categóricas
    ],
    remainder='passthrough'  # Mantener las columnas numéricas sin cambios
)

# Bloque 5: Modelo de Bosques Aleatorios
random_forest_model = RandomForestClassifier(
    n_estimators=100,        # Número de árboles
    max_depth=None,          # Sin límite para la profundidad de los árboles
    random_state=42          # Asegurar reproducibilidad
)

# Bloque 6: Crear el Pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),  # Preprocesar los datos
    ('classifier', random_forest_model)  # Modelo de Bosques Aleatorios
])

# Bloque 7: Entrenar el Pipeline con el conjunto de entrenamiento
pipeline.fit(x_train, y_train)

# Bloque 8: Probar el Pipeline con el conjunto de prueba
##predictions = pipeline.predict(x_test)

# Mostrar un ejemplo de las predicciones
##print("Predicciones de prueba:", predictions[:10])

c:\Users\usuario\OneDrive\Escritorio\Posgrado\Predictiva\2024-2-LAB-01-prediccion-del-default-usando-rf-dzaptaca\.venv\lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  Pipeline(steps=[('cast_to_int',
                                                                   CastToInteger(columns=['SEX',
                                                                                          'EDUCATION',
                                                                                          'MARRIAGE'])),
                                                                  ('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['SEX', 'EDUCATION',
                                                   'MARRIAGE'])])),
                ('classifier', RandomForestClassifier(random_state=42))])